export enum TransactionIcon {
  HouseUser = "HouseUserIcon",
  Bolt = "BoltIcon",
  Water = "WaterIcon",
  Fire = "FireIcon",
  Viande = "ViandeIcon",
  Pizza = "PizzaIcon",
  WineGlass = "WineGlassIcon",
  Coffee = "CoffeeIcon",
  IceCream = "IceCreamIcon",
  Globe = "GlobeIcon",
  Phone = "PhoneIcon",
  Tv = "TvIcon",
  Dumbbell = "DumbbellIcon",
  Film = "FilmIcon",
  PersonWalking = "PersonWalkingIcon",
  Scisor = "ScisorIcon",
  SpraySparkles = "SpraySparklesIcon",
  Medical = "MedicalIcon",
  Tablets = "TabletsIcon",
  Bus = "BusIcon",
  Parking = "ParkingIcon",
  Gauge = "GaugeIcon",
  CarBurst = "CarBurstIcon",
  HouseFire = "HouseFireIcon",
  FileMedical = "FileMedicalIcon",
  CarOn = "CarOnIcon",
  Car = "CarIcon",
  Taxi = "TaxiIcon",
  Award = "AwardIcon",
  WandMagic = "WandMagicIcon",
  Question = "QuestionIcon",
  Mountain = "MountainIcon",
  Gift = "GiftIcon",
  Shirt = "ShirtIcon",
  Game = "GameIcon",
  School = "SchoolIcon",
  Book = "BookIcon",
  BasketFill = "BasketFillIcon",
  PeggyBank = "PeggyBankIcon",
  SackDollar = "SackDollarIcon",
  MoneyBillWave = "MoneyBillWaveIcon",
  CircleDollarToSlot = "CircleDollarToSlotIcon",
  HandHoldingDollar = "HandHoldingDollarIcon",
  Landmark = "LandmarkIcon",
  MoneyBillTrendUp = "MoneyBillTrendUpIcon",
}
export const TRANSACTION_ICON_CATEGORY = Object.values(TransactionIcon);

export const defaultCategories: string[] = [
  "Alimentation",
  "Restaurants & Fast-food",
  "Cafés & Bars",
  "Logement & Charges",
  "Électricité & Eau",
  "Internet & Téléphone",
  "Transport & Essence",
  "Santé & Médicaments",
  "Assurance",
  "Sport & Fitness",
  "Divertissement & Loisirs",
  "Voyages & Vacances",
  "Éducation & Livres",
  "Vêtements & Accessoires",
  "Cadeaux & Événements",
  "Impôts & Taxes",
  "Autres dépenses",
  "Salaire",
  "Prime",
  "Investissements",
  "Économies",
  "Remboursement & Prêt",
  "Revenus locatifs",
  "Ventes & Revente",
  "Aides & Subventions",
  "Autres revenus",
];