import { handleDBError } from "../utils/handleCoreResponse";
import { DBConnection  } from "../config/db";
import { Table } from "ts-sql-query/Table";

const tNewsletter = new (class extends Table<DBConnection, "tNewsletter"> {
  id = this.autogeneratedPrimaryKey("id", "int");
  email = this.column("email", "string");
  constructor() {
    super("newsletter");
  }
})();

export class Newsletter {
  static async insert(email: string) {
    return new DBConnection()
      .insertInto(tNewsletter)
      .set({ email })
      .executeInsert()
      .catch(handleDBError("insert", "newsletter"));
  }

  static async sizeDB() {
    return new DBConnection()
      .selectFrom(tNewsletter)
      .selectCountAll()
      .executeSelectOne();
  }
}